# Notebook to debug functions

In [71]:
import tensorflow as tf
import numpy as np

In [72]:
daily_sales = np.arange(0,12)
ds = tf.data.Dataset.from_tensor_slices(daily_sales)
ds

<TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [73]:
ds = ds.batch(2).shuffle(10)

In [74]:
len(ds)

6

In [70]:
for item in ds.take(5):
    print(item)


tf.Tensor(
[[8 9]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 2  3]
 [10 11]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[6 7]
 [0 1]], shape=(2, 2), dtype=int32)
