# Find delay with deep network

In [1]:
import numpy as np

from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.utils import np_utils

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

## Data

In [2]:
ds = np.load(r"..\datasets\isia_flow_similarity_with_delay.npy", allow_pickle=True)

In [4]:
ds_test = np.load(r"..\datasets\click_flow_similarity_with_delay.npy", allow_pickle=True)

## Delay between -1 to 9

In [5]:
tmp = ds.tolist()
data = []
for i in range(len(tmp)):
    if tmp[i][1]!=-1 and tmp[i][1]<10:
        data.append(tmp[i])

data = np.array(data, dtype=object)

X = data[:,0].tolist()
y = data[:,1].tolist()

In [6]:
X_train = np.array(X)
y_train = np_utils.to_categorical(y, num_classes=10)
# X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.1, random_state=42, stratify=y)

In [17]:
modelSmallDelay = Sequential([
    Dense(64, input_dim = 400, activation="relu"),
    Dropout(0.2),
    Dense(32, activation="relu"),
    Dropout(0.4),
    Dense(10, activation="softmax")
])

modelSmallDelay.compile(loss='categorical_crossentropy', optimizer="adam", metrics=['accuracy'])

In [18]:
modelSmallDelay.fit(X_train, y_train, epochs=500)

Epoch 1/400
190/190 [==============================] - 1s 2ms/step - loss: 2.2850 - accuracy: 0.1316
Epoch 2/400
190/190 [==============================] - 0s 2ms/step - loss: 2.1640 - accuracy: 0.1898
Epoch 3/400
190/190 [==============================] - 0s 2ms/step - loss: 2.0053 - accuracy: 0.2646
Epoch 4/400
190/190 [==============================] - 0s 2ms/step - loss: 1.8219 - accuracy: 0.3378
Epoch 5/400
190/190 [==============================] - 0s 2ms/step - loss: 1.6762 - accuracy: 0.3837
Epoch 6/400
190/190 [==============================] - 0s 2ms/step - loss: 1.5151 - accuracy: 0.4450
Epoch 7/400
190/190 [==============================] - 0s 2ms/step - loss: 1.3853 - accuracy: 0.5069
Epoch 8/400
190/190 [==============================] - 0s 2ms/step - loss: 1.3096 - accuracy: 0.5401
Epoch 9/400
190/190 [==============================] - 0s 2ms/step - loss: 1.2303 - accuracy: 0.5733
Epoch 10/400
190/190 [==============================] - 0s 2ms/step - loss: 1.1319 - accura

In [22]:
tmp = ds_test.tolist()
data = []
for i in range(len(tmp)):
    if tmp[i][1]!=-1 and tmp[i][1]<10:
        data.append(tmp[i])

data = np.array(data, dtype=object)

X_test = data[:,0].tolist()
y_test = data[:,1].tolist()

In [23]:
X_test = np.array(X_test)
y_test = np_utils.to_categorical(y_test, num_classes=10)

In [24]:
modelSmallDelay.evaluate(X_test, y_test)

8/8 [==============================] - 0s 7ms/step - loss: 0.6533 - accuracy: 0.9000


[0.6532905697822571, 0.8999999761581421]

In [25]:
y_pred_test_prob = modelSmallDelay.predict(X_test)

8/8 [==============================] - 0s 3ms/step


In [26]:
y_pred_test = []
for i in range(len(y_pred_test_prob)):
    y_pred_test.append(np.argmax(y_pred_test_prob[i]))

In [27]:
y_test_index = []
for i in range(len(y_test)):
    y_test_index.append(np.argmax(y_test[i]))

In [28]:
print(classification_report(y_test_index, y_pred_test))

              precision    recall  f1-score   support

           0       0.96      0.90      0.93        29
           1       0.91      0.97      0.94        30
           2       0.93      0.93      0.93        30
           3       0.95      0.91      0.93        22
           4       1.00      0.77      0.87        22
           5       0.89      0.96      0.93        26
           6       0.91      0.83      0.87        24
           7       0.77      0.89      0.83        19
           8       0.86      0.95      0.90        19
           9       0.80      0.84      0.82        19

    accuracy                           0.90       240
   macro avg       0.90      0.90      0.89       240
weighted avg       0.91      0.90      0.90       240



In [16]:
print(confusion_matrix(y_true=y_test_index, y_pred=y_pred_test))

[[26  0  0  0  0  1  0  0  1  1]
 [ 0 30  0  0  0  0  0  0  0  0]
 [ 1  0 27  1  0  1  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  2]
 [ 1  2  0  0 17  0  0  0  1  1]
 [ 0  1  1  0  0 23  0  0  1  0]
 [ 0  1  0  0  0  0 18  2  1  2]
 [ 0  0  1  0  0  0  0 17  1  0]
 [ 0  0  0  0  0  0  0  1 18  0]
 [ 0  0  0  1  0  0  0  1  1 16]]


## Delay between 0 to 20

In [36]:
data = ds.tolist()

for i in range(len(data)):
    if data[i][1] == 20: data[i][1] = -1

data = np.array(data, dtype=object)

X = data[:,0].tolist()
y = data[:,1].tolist()

In [37]:
X_train = np.array(X)
y_train = np_utils.to_categorical(y, num_classes=21)
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42, stratify=y)

In [38]:
modelFullDelay = Sequential([
    Dense(64, input_dim = 400, activation="relu"),
    Dropout(0.2),
    Dense(32, activation="relu"),
    Dropout(0.4),
    Dense(21, activation="softmax")
])

modelFullDelay.compile(loss='categorical_crossentropy', optimizer="adam", metrics=['accuracy'])

In [39]:
modelFullDelay.fit(X_train, y_train, epochs=400)

Epoch 1/400
383/383 [==============================] - 3s 4ms/step - loss: 3.0097 - accuracy: 0.0715
Epoch 2/400
383/383 [==============================] - 2s 4ms/step - loss: 2.8411 - accuracy: 0.0974
Epoch 3/400
383/383 [==============================] - 2s 4ms/step - loss: 2.7030 - accuracy: 0.1286
Epoch 4/400
383/383 [==============================] - 2s 4ms/step - loss: 2.5979 - accuracy: 0.1570
Epoch 5/400
383/383 [==============================] - 2s 4ms/step - loss: 2.5173 - accuracy: 0.1791
Epoch 6/400
383/383 [==============================] - 2s 4ms/step - loss: 2.4332 - accuracy: 0.2074
Epoch 7/400
383/383 [==============================] - 2s 4ms/step - loss: 2.3647 - accuracy: 0.2303
Epoch 8/400
383/383 [==============================] - 2s 4ms/step - loss: 2.2824 - accuracy: 0.2638
Epoch 9/400
383/383 [==============================] - 2s 4ms/step - loss: 2.2200 - accuracy: 0.2859
Epoch 10/400
383/383 [==============================] - 1s 4ms/step - loss: 2.1493 - accura

In [40]:
data = ds_test.tolist()

for i in range(len(data)):
    if data[i][1] == 20: data[i][1] = -1

data = np.array(data, dtype=object)

X = data[:,0].tolist()
y = data[:,1].tolist()

In [41]:
X_test = np.array(X)
y_test = np_utils.to_categorical(y, num_classes=21)
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42, stratify=y)

In [42]:
modelFullDelay.evaluate(X_test, y_test)

16/16 [==============================] - 0s 1ms/step - loss: 2.1138 - accuracy: 0.6600


[2.1137566566467285, 0.6600000262260437]

In [44]:
y_pred_test_prob = modelFullDelay.predict(X_test)

16/16 [==============================] - 0s 1ms/step


In [45]:
y_pred_test = []
for i in range(len(y_pred_test_prob)):
    y_pred_test.append(np.argmax(y_pred_test_prob[i]))

In [46]:
y_test_index = []
for i in range(len(y_test)):
    y_test_index.append(np.argmax(y_test[i]))

In [47]:
print(classification_report(y_test_index, y_pred_test))

              precision    recall  f1-score   support

           0       0.96      0.76      0.85        29
           1       0.82      0.93      0.87        30
           2       0.84      0.87      0.85        30
           3       0.80      0.91      0.85        22
           4       0.83      0.68      0.75        22
           5       0.79      0.73      0.76        26
           6       0.88      0.62      0.73        24
           7       0.74      0.74      0.74        19
           8       0.63      0.89      0.74        19
           9       0.78      0.74      0.76        19
          10       0.92      0.96      0.94        23
          11       0.60      0.50      0.55        18
          12       0.64      0.69      0.67        26
          13       0.61      0.52      0.56        21
          14       0.57      0.57      0.57        21
          15       0.44      0.55      0.49        22
          16       0.46      0.52      0.49        21
          17       0.35    

In [48]:
print(confusion_matrix(y_true=y_test_index, y_pred=y_pred_test))

[[22  1  0  0  0  1  0  0  1  0  0  3  0  1  0  0  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0]
 [ 0  0 26  0  0  0  0  0  0  1  0  0  0  1  0  2  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0]
 [ 0  0  0  0 15  0  0  0  1  0  0  0  2  0  0  3  0  0  0  0  1]
 [ 0  1  0  0  0 19  0  0  1  0  0  0  0  0  0  0  5  0  0  0  0]
 [ 1  0  1  0  0  0 15  1  0  0  0  1  0  0  0  0  0  3  1  0  1]
 [ 0  0  0  0  0  0  1 14  0  0  0  0  1  0  0  0  0  0  2  1  0]
 [ 0  0  0  0  0  0  0  2 17  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  0 14  0  0  0  0  1  0  0  1  0  0  2]
 [ 0  0  0  0  0  0  0  0  0  1 22  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  2  0  1  9  1  1  0  0  0  0  0  2  1]
 [ 0  3  0  1  0  0  0  0  2  0  0  0 18  0  0  0  0  0  0  1  1]
 [ 0  0  3  0  0  0  0  0  0  0  0  0  0 11  2  0  0  0  1  2  2]
 [ 0  0  0  3  0  1  1  0  0  0  0  0  0  2 12  0  0  2  0  0  0]
 [ 0  0  0