# Find delay with deep network

In [1]:
import numpy as np

from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.utils import np_utils

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

## Data

In [4]:
ds = np.load(r"..\datasets\isia_flow_similarity_with_delay.npy", allow_pickle=True)

## Delay between -1 to 9

In [6]:
tmp = ds.tolist()
data = []
for i in range(len(tmp)):
    if tmp[i][1]!=-1 and tmp[i][1]<10:
        data.append(tmp[i])

data = np.array(data, dtype=object)

X = data[:,0].tolist()
y = data[:,1].tolist()

In [7]:
X = np.array(X)
y = np_utils.to_categorical(y, num_classes=10)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42, stratify=y)

In [8]:
modelSmallDelay = Sequential([
    Dense(64, input_dim = 400, activation="relu"),
    Dropout(0.2),
    Dense(32, activation="relu"),
    Dropout(0.4),
    Dense(10, activation="softmax")
])

modelSmallDelay.compile(loss='categorical_crossentropy', optimizer="adam", metrics=['accuracy'])

In [10]:
modelSmallDelay.fit(X_train, y_train, epochs=500)

Epoch 1/500
130/130 [==============================] - 1s 2ms/step - loss: 2.3015 - accuracy: 0.1209
Epoch 2/500
130/130 [==============================] - 0s 2ms/step - loss: 2.2254 - accuracy: 0.1753
Epoch 3/500
130/130 [==============================] - 0s 2ms/step - loss: 2.0930 - accuracy: 0.2287
Epoch 4/500
130/130 [==============================] - 0s 2ms/step - loss: 1.9594 - accuracy: 0.2748
Epoch 5/500
130/130 [==============================] - 0s 2ms/step - loss: 1.8530 - accuracy: 0.3157
Epoch 6/500
130/130 [==============================] - 0s 2ms/step - loss: 1.7233 - accuracy: 0.3734
Epoch 7/500
130/130 [==============================] - 0s 2ms/step - loss: 1.6083 - accuracy: 0.4280
Epoch 8/500
130/130 [==============================] - 0s 2ms/step - loss: 1.4963 - accuracy: 0.4797
Epoch 9/500
130/130 [==============================] - 0s 2ms/step - loss: 1.3847 - accuracy: 0.5234
Epoch 10/500
130/130 [==============================] - 0s 2ms/step - loss: 1.3341 - accura

In [11]:
modelSmallDelay.evaluate(X_test, y_test)

15/15 [==============================] - 0s 1ms/step - loss: 0.9167 - accuracy: 0.8531


[0.9167454242706299, 0.8531317710876465]

In [12]:
y_pred_test_prob = modelSmallDelay.predict(X_test)

15/15 [==============================] - 0s 1ms/step


In [13]:
y_pred_test = []
for i in range(len(y_pred_test_prob)):
    y_pred_test.append(np.argmax(y_pred_test_prob[i]))

In [14]:
y_test_index = []
for i in range(len(y_test)):
    y_test_index.append(np.argmax(y_test[i]))

In [15]:
print(classification_report(y_test_index, y_pred_test))

              precision    recall  f1-score   support

           0       0.93      0.89      0.91        45
           1       1.00      0.85      0.92        48
           2       0.69      0.93      0.79        43
           3       0.89      0.87      0.88        46
           4       0.97      0.79      0.87        47
           5       0.85      0.87      0.86        46
           6       0.84      0.89      0.86        46
           7       0.90      0.79      0.84        47
           8       0.76      0.90      0.82        49
           9       0.81      0.76      0.79        46

    accuracy                           0.85       463
   macro avg       0.86      0.85      0.85       463
weighted avg       0.87      0.85      0.85       463



In [16]:
print(confusion_matrix(y_true=y_test_index, y_pred=y_pred_test))

[[40  0  2  2  0  0  0  0  0  1]
 [ 0 41  4  1  0  2  0  0  0  0]
 [ 1  0 40  0  0  0  0  0  1  1]
 [ 0  0  1 40  0  0  1  2  2  0]
 [ 0  0  3  1 37  3  1  1  0  1]
 [ 0  0  3  1  0 40  1  1  0  0]
 [ 0  0  1  0  0  1 41  0  2  1]
 [ 0  0  1  0  1  0  2 37  3  3]
 [ 0  0  1  0  0  0  3  0 44  1]
 [ 2  0  2  0  0  1  0  0  6 35]]


## Delay between 0 to 20

In [17]:
data = ds.tolist()

for i in range(len(data)):
    if data[i][1] == 20: data[i][1] = -1

data = np.array(data, dtype=object)

X = data[:,0].tolist()
y = data[:,1].tolist()

In [18]:
X = np.array(X)
y = np_utils.to_categorical(y, num_classes=21)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42, stratify=y)

In [19]:
modelFullDelay = Sequential([
    Dense(64, input_dim = 400, activation="relu"),
    Dropout(0.2),
    Dense(32, activation="relu"),
    Dropout(0.4),
    Dense(21, activation="softmax")
])

modelFullDelay.compile(loss='categorical_crossentropy', optimizer="adam", metrics=['accuracy'])

In [29]:
modelFullDelay.fit(X_train, y_train, epochs=400)

Epoch 1/200
261/261 [==============================] - 0s 2ms/step - loss: 0.8285 - accuracy: 0.7312
Epoch 2/200
261/261 [==============================] - 0s 1ms/step - loss: 0.8015 - accuracy: 0.7371
Epoch 3/200
261/261 [==============================] - 0s 1ms/step - loss: 0.8497 - accuracy: 0.7285
Epoch 4/200
261/261 [==============================] - 0s 1ms/step - loss: 0.7922 - accuracy: 0.7428
Epoch 5/200
261/261 [==============================] - 0s 1ms/step - loss: 0.7512 - accuracy: 0.7586
Epoch 6/200
261/261 [==============================] - 0s 2ms/step - loss: 0.7702 - accuracy: 0.7510
Epoch 7/200
261/261 [==============================] - 1s 2ms/step - loss: 0.7723 - accuracy: 0.7523
Epoch 8/200
261/261 [==============================] - 0s 2ms/step - loss: 0.7701 - accuracy: 0.7535
Epoch 9/200
261/261 [==============================] - 0s 2ms/step - loss: 0.7607 - accuracy: 0.7469
Epoch 10/200
261/261 [==============================] - 0s 2ms/step - loss: 0.7914 - accura

In [30]:
modelFullDelay.evaluate(X_test, y_test)

29/29 [==============================] - 0s 1ms/step - loss: 2.6421 - accuracy: 0.5849


[2.6420528888702393, 0.5848648548126221]

In [22]:
y_pred_test_prob = modelFullDelay.predict(X_test)

29/29 [==============================] - 0s 1ms/step


In [23]:
y_pred_test = []
for i in range(len(y_pred_test_prob)):
    y_pred_test.append(np.argmax(y_pred_test_prob[i]))

In [24]:
y_test_index = []
for i in range(len(y_test)):
    y_test_index.append(np.argmax(y_test[i]))

In [25]:
print(classification_report(y_test_index, y_pred_test))

              precision    recall  f1-score   support

           0       0.76      0.78      0.77        45
           1       0.86      0.77      0.81        48
           2       0.86      0.72      0.78        43
           3       0.63      0.72      0.67        46
           4       0.77      0.70      0.73        47
           5       0.80      0.61      0.69        46
           6       0.74      0.76      0.75        46
           7       0.70      0.60      0.64        47
           8       0.76      0.63      0.69        49
           9       0.69      0.59      0.64        46
          10       0.63      0.63      0.63        46
          11       0.55      0.47      0.51        36
          12       0.55      0.50      0.53        42
          13       0.50      0.51      0.51        41
          14       0.40      0.59      0.48        41
          15       0.39      0.49      0.43        41
          16       0.39      0.40      0.40        40
          17       0.45    

In [26]:
print(confusion_matrix(y_true=y_test_index, y_pred=y_pred_test))

[[35  0  0  0  0  0  0  0  0  0  0  8  0  0  1  0  0  0  0  1  0]
 [ 2 37  0  0  1  2  0  2  0  0  1  0  2  0  0  0  0  0  0  0  1]
 [ 2  0 31  3  1  1  0  1  0  0  0  0  0  4  0  0  0  0  0  0  0]
 [ 3  1  2 33  0  0  0  0  0  0  0  0  0  0  3  3  1  0  0  0  0]
 [ 0  0  0  0 33  1  0  0  1  1  0  0  0  1  1  8  0  1  0  0  0]
 [ 0  0  1  0  0 28  2  1  1  1  1  0  0  1  0  0  8  0  0  0  2]
 [ 0  0  0  2  1  0 35  0  2  0  1  1  1  0  0  0  0  2  0  0  1]
 [ 0  0  0  0  0  1  1 28  0  0  0  0  0  0  1  0  0  1 14  0  1]
 [ 0  0  0  0  0  0  1  1 31  2  0  0  2  0  1  0  1  0  5  5  0]
 [ 0  1  0  1  1  0  0  0  1 27  4  0  4  1  0  0  0  0  0  0  6]
 [ 0  0  0  0  1  0  1  0  0  0 29  0  2  3  1  0  1  0  1  1  6]
 [ 3  0  0  1  0  0  0  0  1  1  3 17  2  1  1  2  0  2  0  2  0]
 [ 1  3  0  1  0  0  1  0  0  1  2  1 21  4  2  0  2  1  1  0  1]
 [ 0  0  1  1  0  0  0  0  1  0  0  0  2 21  5  3  1  1  1  2  2]
 [ 0  0  0  6  0  0  0  0  0  0  0  1  0  1 24  3  1  2  0  1  2]
 [ 0  0  0