# Find delay with deep network

In [1]:
import numpy as np

from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.utils import np_utils

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

## Data

In [2]:
ds = np.load(r"..\datasets\isia_flow_similarity_with_delay.npy", allow_pickle=True)

In [4]:
ds_test = np.load(r"..\datasets\click_flow_similarity_with_delay.npy", allow_pickle=True)

## Delay between 0 to 9

In [3]:
tmp = ds.tolist()
data = []
for i in range(len(tmp)):
    if tmp[i][1]!=-1 and tmp[i][1]<10:
        data.append(tmp[i])

data = np.array(data, dtype=object)

X = data[:,0].tolist()
y = data[:,1].tolist()

In [4]:
X_train = np.array(X)
y_train = np_utils.to_categorical(y, num_classes=10)
# X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.1, random_state=42, stratify=y)

In [5]:
modelSmallDelay = Sequential([
    Dense(64, input_dim = 400, activation="relu"),
    Dropout(0.2),
    Dense(32, activation="relu"),
    Dropout(0.4),
    Dense(10, activation="softmax")
])

modelSmallDelay.compile(loss='categorical_crossentropy', optimizer="adam", metrics=['accuracy'])

In [6]:
modelSmallDelay.fit(X_train, y_train, epochs=500)

Epoch 1/500
190/190 [==============================] - 1s 2ms/step - loss: 2.2889 - accuracy: 0.1270
Epoch 2/500
190/190 [==============================] - 0s 2ms/step - loss: 2.1656 - accuracy: 0.1829
Epoch 3/500
190/190 [==============================] - 0s 2ms/step - loss: 2.0032 - accuracy: 0.2464
Epoch 4/500
190/190 [==============================] - 0s 2ms/step - loss: 1.8351 - accuracy: 0.3190
Epoch 5/500
190/190 [==============================] - 0s 2ms/step - loss: 1.6774 - accuracy: 0.3888
Epoch 6/500
190/190 [==============================] - 0s 2ms/step - loss: 1.5040 - accuracy: 0.4637
Epoch 7/500
190/190 [==============================] - 0s 2ms/step - loss: 1.3833 - accuracy: 0.5221
Epoch 8/500
190/190 [==============================] - 0s 2ms/step - loss: 1.2513 - accuracy: 0.5783
Epoch 9/500
190/190 [==============================] - 0s 3ms/step - loss: 1.1434 - accuracy: 0.6193
Epoch 10/500
190/190 [==============================] - 0s 2ms/step - loss: 1.0678 - accura

In [7]:
tmp = ds_test.tolist()
data = []
for i in range(len(tmp)):
    if tmp[i][1]!=-1 and tmp[i][1]<10:
        data.append(tmp[i])

data = np.array(data, dtype=object)

X_test = data[:,0].tolist()
y_test = data[:,1].tolist()

NameError: name 'ds_test' is not defined

In [10]:
X_test = np.array(X_test)
y_test = np_utils.to_categorical(y_test, num_classes=10)

In [11]:
modelSmallDelay.evaluate(X_test, y_test)

8/8 [==============================] - 0s 1ms/step - loss: 1.8331 - accuracy: 0.7382


[1.8330625295639038, 0.7381974458694458]

In [12]:
y_pred_test_prob = modelSmallDelay.predict(X_test)

8/8 [==============================] - 0s 1ms/step


In [13]:
y_pred_test = []
for i in range(len(y_pred_test_prob)):
    y_pred_test.append(np.argmax(y_pred_test_prob[i]))

In [14]:
y_test_index = []
for i in range(len(y_test)):
    y_test_index.append(np.argmax(y_test[i]))

In [15]:
print(classification_report(y_test_index, y_pred_test))

              precision    recall  f1-score   support

           0       0.88      0.68      0.77        22
           1       0.79      0.90      0.84        29
           2       0.69      0.67      0.68        27
           3       0.81      0.81      0.81        21
           4       0.76      0.57      0.65        23
           5       0.73      0.42      0.53        19
           6       0.57      0.71      0.63        17
           7       0.55      0.75      0.63        16
           8       0.79      0.85      0.81        26
           9       0.78      0.88      0.83        33

    accuracy                           0.74       233
   macro avg       0.74      0.72      0.72       233
weighted avg       0.75      0.74      0.73       233



In [16]:
print(confusion_matrix(y_true=y_test_index, y_pred=y_pred_test))

[[26  0  0  0  0  1  0  0  1  1]
 [ 0 30  0  0  0  0  0  0  0  0]
 [ 1  0 27  1  0  1  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  2]
 [ 1  2  0  0 17  0  0  0  1  1]
 [ 0  1  1  0  0 23  0  0  1  0]
 [ 0  1  0  0  0  0 18  2  1  2]
 [ 0  0  1  0  0  0  0 17  1  0]
 [ 0  0  0  0  0  0  0  1 18  0]
 [ 0  0  0  1  0  0  0  1  1 16]]


## Delay between 0 to 20

In [16]:
data = ds.tolist()

for i in range(len(data)):
    if data[i][1] == 20: data[i][1] = -1

data = np.array(data, dtype=object)

X = data[:,0].tolist()
y = data[:,1].tolist()

In [17]:
X_train = np.array(X)
y_train = np_utils.to_categorical(y, num_classes=21)
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42, stratify=y)

In [18]:
modelFullDelay = Sequential([
    Dense(64, input_dim = 400, activation="relu"),
    Dropout(0.2),
    Dense(32, activation="relu"),
    Dropout(0.4),
    Dense(21, activation="softmax")
])

modelFullDelay.compile(loss='categorical_crossentropy', optimizer="adam", metrics=['accuracy'])

In [19]:
modelFullDelay.fit(X_train, y_train, epochs=400)

Epoch 1/400
383/383 [==============================] - 1s 2ms/step - loss: 3.0341 - accuracy: 0.0612
Epoch 2/400
383/383 [==============================] - 1s 2ms/step - loss: 2.8964 - accuracy: 0.0932
Epoch 3/400
383/383 [==============================] - 1s 2ms/step - loss: 2.7660 - accuracy: 0.1168
Epoch 4/400
383/383 [==============================] - 1s 2ms/step - loss: 2.6444 - accuracy: 0.1543
Epoch 5/400
383/383 [==============================] - 1s 2ms/step - loss: 2.5625 - accuracy: 0.1844
Epoch 6/400
383/383 [==============================] - 1s 2ms/step - loss: 2.4526 - accuracy: 0.2107
Epoch 7/400
383/383 [==============================] - 1s 2ms/step - loss: 2.3617 - accuracy: 0.2402
Epoch 8/400
383/383 [==============================] - 1s 2ms/step - loss: 2.2890 - accuracy: 0.2688
Epoch 9/400
383/383 [==============================] - 1s 2ms/step - loss: 2.2168 - accuracy: 0.2933
Epoch 10/400
383/383 [==============================] - 1s 2ms/step - loss: 2.1622 - accura

In [20]:
data = ds_test.tolist()

for i in range(len(data)):
    if data[i][1] == 20: data[i][1] = -1

data = np.array(data, dtype=object)

X = data[:,0].tolist()
y = data[:,1].tolist()

In [21]:
X_test = np.array(X)
y_test = np_utils.to_categorical(y, num_classes=21)
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42, stratify=y)

In [22]:
modelFullDelay.evaluate(X_test, y_test)

16/16 [==============================] - 0s 1ms/step - loss: 6.9937 - accuracy: 0.2590


[6.993699073791504, 0.2590361535549164]

In [23]:
y_pred_test_prob = modelFullDelay.predict(X_test)

16/16 [==============================] - 0s 1ms/step


In [24]:
y_pred_test = []
for i in range(len(y_pred_test_prob)):
    y_pred_test.append(np.argmax(y_pred_test_prob[i]))

In [25]:
y_test_index = []
for i in range(len(y_test)):
    y_test_index.append(np.argmax(y_test[i]))

In [26]:
print(classification_report(y_test_index, y_pred_test))

              precision    recall  f1-score   support

           0       0.67      0.36      0.47        22
           1       0.65      0.38      0.48        29
           2       0.62      0.30      0.40        27
           3       1.00      0.19      0.32        21
           4       0.80      0.35      0.48        23
           5       0.40      0.21      0.28        19
           6       0.67      0.12      0.20        17
           7       0.12      0.12      0.12        16
           8       0.33      0.35      0.34        26
           9       0.48      0.30      0.37        33
          10       0.75      0.22      0.34        27
          11       0.40      0.19      0.26        21
          12       0.50      0.30      0.37        30
          13       0.29      0.21      0.24        24
          14       0.16      0.20      0.18        15
          15       0.35      0.28      0.31        25
          16       0.10      0.13      0.12        23
          17       0.10    

In [27]:
print(confusion_matrix(y_true=y_test_index, y_pred=y_pred_test))

[[ 8  2  1  0  0  1  0  2  2  0  0  0  0  0  0  0  1  0  1  2  2]
 [ 3 11  1  0  0  0  0  2  1  0  0  0  4  0  2  1  1  0  0  2  1]
 [ 0  1  8  0  0  0  0  3  3  0  0  0  0  4  0  0  1  1  4  2  0]
 [ 0  1  1  4  0  0  0  0  2  0  0  1  0  1  6  0  0  1  0  3  1]
 [ 0  0  1  0  8  1  1  1  2  2  0  0  0  0  0  3  1  1  0  0  2]
 [ 0  0  0  0  0  4  0  0  0  0  0  0  0  0  1  0  8  1  2  0  3]
 [ 0  1  0  0  0  0  2  1  0  0  0  0  0  0  0  0  1  9  0  1  2]
 [ 0  0  1  0  0  0  0  2  3  0  0  0  2  0  0  0  0  0  6  2  0]
 [ 0  0  0  0  0  0  0  1  9  1  1  0  1  0  0  0  0  0  1 10  2]
 [ 0  0  0  0  0  0  0  0  1 10  0  0  0  0  0  0  0  2  0  1 19]
 [ 0  0  0  0  0  0  0  3  2  1  6  1  1  0  0  1  1  0  2  4  5]
 [ 0  0  0  0  0  1  0  0  0  0  0  4  0  0  0  2  4  0  0  6  4]
 [ 0  0  0  0  0  0  0  0  0  2  1  1  9  3  0  1  0  0  3  5  5]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  5  2  0  0  2  1 10  3]
 [ 0  0  0  0  0  0  0  0  0  1  0  0  0  0  3  2  0  2  2  1  4]
 [ 0  0  0