# Find delay with deep network

In [1]:
import numpy as np

from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.utils import np_utils

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

## Data

In [2]:
ds = np.load(r"..\datasets\isia_flow_similarity_with_delay.npy", allow_pickle=True)

In [25]:
ds_test = np.load(r"..\datasets\click_flow_similarity_with_delay.npy", allow_pickle=True)

## Delay between -1 to 9

In [3]:
tmp = ds.tolist()
data = []
for i in range(len(tmp)):
    if tmp[i][1]!=-1 and tmp[i][1]<10:
        data.append(tmp[i])

data = np.array(data, dtype=object)

X = data[:,0].tolist()
y = data[:,1].tolist()

In [4]:
X_train = np.array(X)
y_train = np_utils.to_categorical(y, num_classes=10)
# X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.1, random_state=42, stratify=y)

In [5]:
modelSmallDelay = Sequential([
    Dense(64, input_dim = 400, activation="relu"),
    Dropout(0.2),
    Dense(32, activation="relu"),
    Dropout(0.4),
    Dense(10, activation="softmax")
])

modelSmallDelay.compile(loss='categorical_crossentropy', optimizer="adam", metrics=['accuracy'])

In [6]:
modelSmallDelay.fit(X_train, y_train, epochs=500)

Epoch 1/500
145/145 [==============================] - 1s 2ms/step - loss: 2.3061 - accuracy: 0.1116
Epoch 2/500
145/145 [==============================] - 0s 2ms/step - loss: 2.2445 - accuracy: 0.1473
Epoch 3/500
145/145 [==============================] - 0s 2ms/step - loss: 2.0957 - accuracy: 0.2179
Epoch 4/500
145/145 [==============================] - 0s 2ms/step - loss: 1.9499 - accuracy: 0.2737
Epoch 5/500
145/145 [==============================] - 0s 2ms/step - loss: 1.8224 - accuracy: 0.3289
Epoch 6/500
145/145 [==============================] - 0s 2ms/step - loss: 1.6806 - accuracy: 0.3847
Epoch 7/500
145/145 [==============================] - 0s 2ms/step - loss: 1.5263 - accuracy: 0.4481
Epoch 8/500
145/145 [==============================] - 0s 2ms/step - loss: 1.4276 - accuracy: 0.4948
Epoch 9/500
145/145 [==============================] - 0s 2ms/step - loss: 1.3201 - accuracy: 0.5392
Epoch 10/500
145/145 [==============================] - 0s 2ms/step - loss: 1.2212 - accura

In [38]:
tmp = ds_test.tolist()
data = []
for i in range(len(tmp)):
    if tmp[i][1]!=-1 and tmp[i][1]<10:
        data.append(tmp[i])

data = np.array(data, dtype=object)

X_test = data[:,0].tolist()
y_test = data[:,1].tolist()

In [39]:
X_test = np.array(X_test)
y_test = np_utils.to_categorical(y_test, num_classes=10)

In [28]:
modelSmallDelay.evaluate(X_test, y_test)

8/8 [==============================] - 0s 2ms/step - loss: 0.5416 - accuracy: 0.9167


[0.5415926575660706, 0.9166666865348816]

In [29]:
y_pred_test_prob = modelSmallDelay.predict(X_test)

8/8 [==============================] - 0s 1ms/step


In [30]:
y_pred_test = []
for i in range(len(y_pred_test_prob)):
    y_pred_test.append(np.argmax(y_pred_test_prob[i]))

In [31]:
y_test_index = []
for i in range(len(y_test)):
    y_test_index.append(np.argmax(y_test[i]))

In [32]:
print(classification_report(y_test_index, y_pred_test))

              precision    recall  f1-score   support

           0       0.93      0.93      0.93        29
           1       0.91      1.00      0.95        30
           2       0.93      0.90      0.92        30
           3       0.88      0.95      0.91        22
           4       1.00      0.82      0.90        22
           5       0.93      1.00      0.96        26
           6       1.00      0.79      0.88        24
           7       0.85      0.89      0.87        19
           8       0.86      0.95      0.90        19
           9       0.89      0.89      0.89        19

    accuracy                           0.92       240
   macro avg       0.92      0.91      0.91       240
weighted avg       0.92      0.92      0.92       240



In [33]:
print(confusion_matrix(y_true=y_test_index, y_pred=y_pred_test))

[[27  0  1  0  0  0  0  1  0  0]
 [ 0 30  0  0  0  0  0  0  0  0]
 [ 1  0 27  1  0  0  0  1  0  0]
 [ 0  0  0 21  0  0  0  0  0  1]
 [ 0  2  0  0 18  0  0  0  1  1]
 [ 0  0  0  0  0 26  0  0  0  0]
 [ 1  0  1  1  0  1 19  0  1  0]
 [ 0  1  0  0  0  1  0 17  0  0]
 [ 0  0  0  0  0  0  0  1 18  0]
 [ 0  0  0  1  0  0  0  0  1 17]]


## Delay between 0 to 20

In [40]:
data = ds.tolist()

for i in range(len(data)):
    if data[i][1] == 20: data[i][1] = -1

data = np.array(data, dtype=object)

X = data[:,0].tolist()
y = data[:,1].tolist()

In [41]:
X = np.array(X)
y = np_utils.to_categorical(y, num_classes=21)
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42, stratify=y)

In [42]:
modelFullDelay = Sequential([
    Dense(64, input_dim = 400, activation="relu"),
    Dropout(0.2),
    Dense(32, activation="relu"),
    Dropout(0.4),
    Dense(21, activation="softmax")
])

modelFullDelay.compile(loss='categorical_crossentropy', optimizer="adam", metrics=['accuracy'])

In [43]:
modelFullDelay.fit(X_train, y_train, epochs=400)

Epoch 1/400
261/261 [==============================] - 1s 2ms/step - loss: 3.0511 - accuracy: 0.0526
Epoch 2/400
261/261 [==============================] - 0s 2ms/step - loss: 3.0160 - accuracy: 0.0660
Epoch 3/400
261/261 [==============================] - 0s 2ms/step - loss: 2.9014 - accuracy: 0.0910
Epoch 4/400
261/261 [==============================] - 0s 1ms/step - loss: 2.8028 - accuracy: 0.1104
Epoch 5/400
261/261 [==============================] - 0s 1ms/step - loss: 2.7464 - accuracy: 0.1294
Epoch 6/400
261/261 [==============================] - 0s 1ms/step - loss: 2.6707 - accuracy: 0.1461
Epoch 7/400
261/261 [==============================] - 0s 2ms/step - loss: 2.6079 - accuracy: 0.1644
Epoch 8/400
261/261 [==============================] - 0s 1ms/step - loss: 2.5296 - accuracy: 0.1928
Epoch 9/400
261/261 [==============================] - 0s 1ms/step - loss: 2.4621 - accuracy: 0.2102
Epoch 10/400
261/261 [==============================] - 0s 1ms/step - loss: 2.4032 - accura

In [46]:
data = ds_test.tolist()

for i in range(len(data)):
    if data[i][1] == 20: data[i][1] = -1

data = np.array(data, dtype=object)

X = data[:,0].tolist()
y = data[:,1].tolist()

In [47]:
X_test = np.array(X)
y_test = np_utils.to_categorical(y, num_classes=21)
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42, stratify=y)

In [48]:
modelFullDelay.evaluate(X_test, y_test)

16/16 [==============================] - 0s 1ms/step - loss: 2.3234 - accuracy: 0.6320


[2.323416233062744, 0.6320000290870667]

In [49]:
y_pred_test_prob = modelFullDelay.predict(X_test)

16/16 [==============================] - 0s 934us/step


In [50]:
y_pred_test = []
for i in range(len(y_pred_test_prob)):
    y_pred_test.append(np.argmax(y_pred_test_prob[i]))

In [51]:
y_test_index = []
for i in range(len(y_test)):
    y_test_index.append(np.argmax(y_test[i]))

In [52]:
print(classification_report(y_test_index, y_pred_test))

              precision    recall  f1-score   support

           0       0.81      0.86      0.83        29
           1       0.77      0.80      0.79        30
           2       0.80      0.80      0.80        30
           3       0.80      0.73      0.76        22
           4       0.67      0.73      0.70        22
           5       0.83      0.77      0.80        26
           6       0.68      0.62      0.65        24
           7       0.64      0.74      0.68        19
           8       0.62      0.68      0.65        19
           9       0.74      0.74      0.74        19
          10       0.81      0.91      0.86        23
          11       0.47      0.44      0.46        18
          12       0.59      0.65      0.62        26
          13       0.64      0.76      0.70        21
          14       0.67      0.67      0.67        21
          15       0.56      0.64      0.60        22
          16       0.52      0.52      0.52        21
          17       0.32    

In [26]:
print(confusion_matrix(y_true=y_test_index, y_pred=y_pred_test))

[[35  0  0  0  0  0  0  0  0  0  0  8  0  0  1  0  0  0  0  1  0]
 [ 2 37  0  0  1  2  0  2  0  0  1  0  2  0  0  0  0  0  0  0  1]
 [ 2  0 31  3  1  1  0  1  0  0  0  0  0  4  0  0  0  0  0  0  0]
 [ 3  1  2 33  0  0  0  0  0  0  0  0  0  0  3  3  1  0  0  0  0]
 [ 0  0  0  0 33  1  0  0  1  1  0  0  0  1  1  8  0  1  0  0  0]
 [ 0  0  1  0  0 28  2  1  1  1  1  0  0  1  0  0  8  0  0  0  2]
 [ 0  0  0  2  1  0 35  0  2  0  1  1  1  0  0  0  0  2  0  0  1]
 [ 0  0  0  0  0  1  1 28  0  0  0  0  0  0  1  0  0  1 14  0  1]
 [ 0  0  0  0  0  0  1  1 31  2  0  0  2  0  1  0  1  0  5  5  0]
 [ 0  1  0  1  1  0  0  0  1 27  4  0  4  1  0  0  0  0  0  0  6]
 [ 0  0  0  0  1  0  1  0  0  0 29  0  2  3  1  0  1  0  1  1  6]
 [ 3  0  0  1  0  0  0  0  1  1  3 17  2  1  1  2  0  2  0  2  0]
 [ 1  3  0  1  0  0  1  0  0  1  2  1 21  4  2  0  2  1  1  0  1]
 [ 0  0  1  1  0  0  0  0  1  0  0  0  2 21  5  3  1  1  1  2  2]
 [ 0  0  0  6  0  0  0  0  0  0  0  1  0  1 24  3  1  2  0  1  2]
 [ 0  0  0